### PR TITLE
fix: overlay IPAM not reporting version

### LINKED ISSUE #2081: overlay IPAM not reporting version
**What happened:** 
when on newly deployed node, checking ipam version shows unknown

image

using
mcr.microsoft.com/containernetworking/cni-dropgz:v0.0.9
mcr.microsoft.com/containernetworking/azure-cns:v1.5.5

maybe @rbtr?

### PR DESCRIPTION
**Pull request by nddq**
**Reason for Change**:

**Issue Fixed**:

Fixes #2081

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

### CODE REVIEW

**Comment by rbtr** [comment]
@nddq what's the output of `./azure-ipam -v` with this change?

File: azure-ipam/internal/buildversion/buildversion.go [hunk 1]
```diff
@@ -1,6 +1,6 @@
-package buildinfo
+package buildversion
```
Comment (thatmattlong) [inline azure-ipam/internal/buildversion/buildversion.go:1]: why renaming and moving these around?

File: Makefile [hunk 2]
```diff
@@ -173,7 +173,7 @@ zapai-version: ## prints the zapai version
 
 # Build the delegated IPAM plugin binary.
 azure-ipam-binary:
-	cd $(AZURE_IPAM_DIR) && CGO_ENABLED=0 go build -v -o $(AZURE_IPAM_BUILD_DIR)/azure-ipam$(EXE_EXT) -ldflags "-X main.version=$(AZURE_IPAM_VERSION)" -gcflags="-dwarflocationlists=true"
+	cd $(AZURE_IPAM_DIR) && CGO_ENABLED=0 go build -v -o $(AZURE_IPAM_BUILD_DIR)/azure-ipam$(EXE_EXT) -ldflags "-X buildversion.BuildVersion=$(AZURE_IPAM_VERSION)" -gcflags="-dwarflocationlists=true"
```
Comment (thatmattlong) [inline Makefile:176]: could just change this to `buildinfo.Version` without renaming/moving the files

Comment (nddq) [reply Makefile:176]: I was trying to match and see if [this](https://github.com/containernetworking/plugins/blob/v1.2.0/pkg/utils/buildversion/buildversion.go) work but no luck. I did tried populating `buildversion.BuildVersion` directly before but no luck either. The only way I managed to get the version printed out is to have the `version` variable inside `main` then populate it through `main.Version` like CNI and CNS does right now. Is this the only way or I'm I missing something?

**Comment by nddq** [comment]
> @nddq what's the output of `./azure-ipam -v` with this change?

image
This is what I got currently. Should azure-ipam have a release tag like v1.xxx+commit like CNI and CNS or is this intended? I remember that we discussed about wanting tagging each plugin and release them individually last summer so it would be great if we could follow up on this was well.

File: Makefile (hunk 2 above)
Comment (rbtr) [reply Makefile:176]: what you're missing is that `main.version` works in _our_ linker args because `main` is the top level package and we have the `version` var defined there. to inject a value more deeply, we need to fully-qualify the path. 

read the comments in the file you linked and check the mentioned "linker script", you'll see how we need to pass the [full path to the `buildversion` package and variable](https://github.com/containernetworking/plugins/blob/v1.2.0/scripts/release.sh#L10C46-L10C129) for the injection to work. we should not need to change anything except the "-X [...]=$(AZURE_IPAM_VERSION)". our Makefile will automatically set that runtime env to either the bare tag if the current revision is tagged, or the latest tag + dirty hash if the current rev is not tagged.

File: azure-ipam/internal/buildversion/buildversion.go (hunk 1 above)
Comment (rbtr) [reply azure-ipam/internal/buildversion/buildversion.go:1]: this file should be deleted entirely

File: Makefile (hunk 2 above)
Comment (nddq) [reply Makefile]: yup, working now

File: azure-ipam/main.go [hunk 3]
```diff
@@ -4,6 +4,7 @@ import (
 	"log"
 	"os"
 
+	"github.com/Azure/azure-container-networking/azure-ipam/internal/buildinfo"
```
Comment (rbtr) [inline azure-ipam/main.go:7]: should we just use the cni buildinfo pkg instead?

Comment (nddq) [reply azure-ipam/main.go:7]: I don't think azure cni has a buildinfo package currently, unless you are talking about a different cni?

Comment (rbtr) [reply azure-ipam/main.go:7]: `github.com/containernetworking/plugins/pkg/utils/buildversion.BuildVersion`

Comment (nddq) [reply azure-ipam/main.go:7]: hmm when I replaced with that pkg, the version became an empty string

**Review by rbtr — APPROVED** [review]

**Review by matmerr — APPROVED** [review]
