### PR TITLE
Fix CNS and CNI ETW log interference issue

### LINKED ISSUE #3691: ETW logging conflict between CNS and CNI
**What happened:** 
When enabling ETW logging via Geneva for both CNS and CNI components, only one of the services emits logs successfully. The other service’s logs are either missing or not routed correctly. This appears to be a conflict in the Geneva logging pipeline.

**What you expected to happen:**  
Both CNS and CNI should be able to emit logs concurrently to Geneva using ETW without interfering with each other’s telemetry.

**How to reproduce it:**  
1. Enable Geneva ETW logging for both CNS and CNI on a Windows node.
2. Use the same Geneva profile name (e.g., ACN-Monitoring) for both services.
3. Observe that only one of the services (typically CNS) emits logs to Geneva, while the other (CNI) does not.

**Orchestrator and Version (e.g. Kubernetes, Docker):**  
Kubernetes (AKS), version details can vary — issue observed in multiple clusters.

**Operating System (Linux/Windows):**  
Windows

**Kernel (e.g. `uanme -a` for Linux or `$(Get-ItemProperty -Path "C:\windows\system32\hal.dll").VersionInfo.FileVersion` for Windows):**
Applicable to Windows kernel versions used in AKS Windows node pools.

**Anything else we need to know?:**
[Miscellaneous information that will assist in solving the issue.]
- Both CNS and CNI are configured to use the same Geneva profile name: ACN-Monitoring.
- This may cause a conflict in the Geneva Monitoring Agent or ETW session registration.
- A workaround might involve assigning unique profile names per component or isolating their ETW providers.

### PR DESCRIPTION
**Pull request by byte-msft**
**Reason for Change**:

This PR addresses a logging conflict between CNS and CNI when both components attempt to emit ETW logs using the same Geneva profile name. Previously, both services were configured to use ACN-Monitoring, which caused one of the services (typically CNI) to fail to emit logs due to ETW session conflicts.

**Changes**
Introduced separate Geneva profile names:
- ACN-Monitoring-CNS for CNS
- ACN-Monitoring-CNI for CNI

**Issue Fixed**:

Fixes #3691

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [X] relevant PR labels added

**Notes**:

### CODE REVIEW

File: cni/log/logger.go [hunk 1]
```diff
@@ -17,7 +17,7 @@ var (
 const (
 	maxLogFileSizeInMb = 5
 	maxLogFileCount    = 8
-	etwCNIEventName    = "Azure-CNI"
+	etwCNIEventName    = "AzureCNI"
```
Comment (rbtr) [inline cni/log/logger.go:20]: does this require downstream changes? are there consumers (like any alerting) which expect the previous event name today?

Comment (byte-msft) [reply cni/log/logger.go:20]: Hi @rbtr 

Currently we are not using ETW streaming at all, and this dash in the name causes an error while streaming logs to Geneva. 

This is the first step of turning on the logging into a Geneva using etw.

**Review by jackieluc — APPROVED** [review]

File: cni/log/logger.go (hunk 1 above)
Comment (msvik) [inline cni/log/logger.go:20]: Curious to know what is this change for?
