### PR TITLE
fix: [NPM] [Linux] race condition when editing NetPol with "except" CIDR

### LINKED ISSUE #2840: [NPM] [Linux] race condition when editing NetPol with "except" CIDR
A race condition occurs when editing a NetworkPolicy with an "except" CIDR block. If there are roughly 5 or more CIDR blocks, one of which has an "except" section, then if the NetworkPolicy is edited (or if the policy is deleted and later recreated), then there is a chance that an NPM Pod enters an incapacitated state where it can't enforce this policy and future policy changes.

### Symptoms
There will be a repeating error log about an unknown argument "nomatch":
```
2024/07/10 23:28:41 [1] [DataPlane] [BACKGROUND] failed to add policy one at a time. default/policy-with-cidr-except. err: [DataPlane] [ADD-NETPOL] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
```

### Prevention and Mitigation
If the issue occurs, restart NPM Pods to mitigate.

The issue can be avoided by:
1. Not editing NetworkPolicy with an "except" CIDR block
2. If a NetworkPolicy exists with an "except" CIDR block and then the policy is deleted, do not create another NetworkPolicy with the same name and namespace.

### Cause
If the race condition is met, then NPM tries to delete the CIDR "except" members from an IPSet, which causes a non-retriable syntax error. The command used is like:
```
ipset -D 10.0.0.0/32 nomatch
```
but it must instead be
```
ipset -D 10.0.0.0/32
```

### PR DESCRIPTION
**Pull request by huntergregory**
Fixes #2840

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [x] relevant PR labels added

### Testing
Verified that the nomatch error does not occur any more on several manual tests.

Performed testing by applying the following NetPol, then editing the except block. There was an indeterministic repro on prior NPM versions.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy-with-cidr-except
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.1.0/24
    - ipBlock:
        cidr: 10.0.2.0/24
    - ipBlock:
        cidr: 10.0.10.0/24
    - ipBlock:
        cidr: 10.0.20.0/24
    - ipBlock:
        cidr: 10.0.30.0/24
    - ipBlock:
        cidr: 10.0.40.0/24
    - ipBlock:
        cidr: 10.0.60.0/24
    - ipBlock:
        cidr: 10.1.0.0/16
        except:
        - 10.1.1.0/24
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.1.0/24
    - ipBlock:
        cidr: 10.0.2.0/24
    - ipBlock:
        cidr: 10.0.10.0/24
    - ipBlock:
        cidr: 10.0.20.0/24
    - ipBlock:
        cidr: 10.0.30.0/24
    - ipBlock:
        cidr: 10.0.40.0/24
    - ipBlock:
        cidr: 10.0.60.0/24
    - ipBlock:
        cidr: 10.1.0.0/16
        except:
        - 10.1.1.0/24
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
```

Logs from repro:
```
I0710 23:28:34.710087       1 dataplane.go:612] [DataPlane] Update Policy called for default/policy-with-cidr-except
I0710 23:28:34.710116       1 dataplane.go:545] [DataPlane] Remove Policy called for default/policy-with-cidr-except
I0710 23:28:34.710201       1 chain-management_linux.go:366] Executing iptables command with args [-w 60 -D AZURE-NPM-INGRESS -j AZURE-NPM-INGRESS-3221666101 -m set --match-set azure-npm-784554818 dst -m comment --comment INGRESS-POLICY-default/policy-with-cidr-except-TO-ns-default-IN-ns-default]
I0710 23:28:34.716043       1 chain-management_linux.go:366] Executing iptables command with args [-w 60 -D AZURE-NPM-EGRESS -j AZURE-NPM-EGRESS-3221666101 -m set --match-set azure-npm-784554818 src -m comment --comment EGRESS-POLICY-default/policy-with-cidr-except-FROM-ns-default-IN-ns-default]
I0710 23:28:34.749957       1 restore.go:188] running this restore command: [iptables-nft-restore -w 60 -T filter --noflush]
I0710 23:28:34.754754       1 dataplane.go:330] [DataPlane] [ApplyDataPlane] [APPLY-DP] starting to apply ipsets
I0710 23:28:34.754793       1 ipsetmanager.go:455] [IPSetManager] dirty caches. toAddUpdateCache: to create: [], to update: [], toDeleteCache: map[cidr-policy-with-cidr-except-in-ns-default-0-0IN:0xc0009b0b00 cidr-policy-with-cidr-except-in-ns-default-0-0OUT:0xc0009b0860 cidr-policy-with-cidr-except-in-ns-default-0-1IN:0xc0009b0b50 cidr-policy-with-cidr-except-in-ns-default-0-1OUT:0xc0009b08b0 cidr-policy-with-cidr-except-in-ns-default-0-2IN:0xc0009b0ba0 cidr-policy-with-cidr-except-in-ns-default-0-2OUT:0xc0009b0900 cidr-policy-with-cidr-except-in-ns-default-0-3IN:0xc0009b0bf0 cidr-policy-with-cidr-except-in-ns-default-0-3OUT:0xc0009b0950 cidr-policy-with-cidr-except-in-ns-default-0-4IN:0xc0009b0c40 cidr-policy-with-cidr-except-in-ns-default-0-4OUT:0xc0009b09a0 cidr-policy-with-cidr-except-in-ns-default-0-5IN:0xc0009b0c90 cidr-policy-with-cidr-except-in-ns-default-0-5OUT:0xc0009b09f0 cidr-policy-with-cidr-except-in-ns-default-0-6IN:0xc0009b0ce0 cidr-policy-with-cidr-except-in-ns-default-0-6OUT:0xc0009b0a40 cidr-policy-with-cidr-except-in-ns-default-0-7IN:0xc0009b0d30 cidr-policy-with-cidr-except-in-ns-default-0-7OUT:0xc0009b0a90]
I0710 23:28:34.754943       1 restore.go:188] running this restore command: [ipset restore]
I0710 23:28:34.761373       1 restore.go:299] continuing after line 17 for command [ipset restore]
I0710 23:28:34.761485       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:34 [1] skipping destroy line for set cidr-policy-with-cidr-except-in-ns-default-0-6OUT since the set is in use by a kernel component
2024/07/10 23:28:34 [1] error: on try number 1, failed to run command [ipset restore]. Rerunning with updated file. err: [line-number error for line [-X azure-npm-2976224028]: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 17: Set cannot be destroyed: it is in use by a kernel component
]]
I0710 23:28:34.763021       1 restore.go:299] continuing after line 1 for command [ipset restore]
I0710 23:28:34.763121       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:34 [1] skipping destroy line for set cidr-policy-with-cidr-except-in-ns-default-0-5OUT since the set is in use by a kernel component
2024/07/10 23:28:34 [1] error: on try number 2, failed to run command [ipset restore]. Rerunning with updated file. err: [line-number error for line [-X azure-npm-1488736011]: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
]]
I0710 23:28:34.765087       1 restore.go:299] continuing after line 1 for command [ipset restore]
I0710 23:28:34.765186       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:34 [1] skipping destroy line for set cidr-policy-with-cidr-except-in-ns-default-0-2IN since the set is in use by a kernel component
2024/07/10 23:28:34 [1] error: on try number 3, failed to run command [ipset restore]. Rerunning with updated file. err: [line-number error for line [-X azure-npm-1687449499]: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
]]
I0710 23:28:34.766865       1 restore.go:299] continuing after line 1 for command [ipset restore]
I0710 23:28:34.766945       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:34 [1] skipping destroy line for set cidr-policy-with-cidr-except-in-ns-default-0-4OUT since the set is in use by a kernel component
2024/07/10 23:28:34 [1] error: on try number 4, failed to run command [ipset restore]. Rerunning with updated file. err: [line-number error for line [-X azure-npm-3478126754]: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
]]
2024/07/10 23:28:34 [1] error: failed to apply ipsets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
]
2024/07/10 23:28:34 [1] syncNetPol error due to error syncing 'default/policy-with-cidr-except': [syncNetPol] error due to  [syncAddAndUpdateNetPol] Error: failed to update translated NPMNetworkPolicy into Dataplane due to [DataPlane] error while updating policy: [DataPlane] [APPLY-DP] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
], requeuing
E0710 23:28:34.769811       1 networkPolicyController.go:195] error syncing 'default/policy-with-cidr-except': [syncNetPol] error due to  [syncAddAndUpdateNetPol] Error: failed to update translated NPMNetworkPolicy into Dataplane due to [DataPlane] error while updating policy: [DataPlane] [APPLY-DP] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 1] and stdErr [ipset v7.5: Error in line 1: Set cannot be destroyed: it is in use by a kernel component
], requeuing
I0710 23:28:34.775238       1 dataplane.go:612] [DataPlane] Update Policy called for default/policy-with-cidr-except
I0710 23:28:34.775257       1 dataplane.go:615] [DataPlane] Policy default/policy-with-cidr-except is not found.
I0710 23:28:34.775263       1 dataplane.go:394] [DataPlane] Add Policy called for default/policy-with-cidr-except
I0710 23:28:34.775267       1 types.go:214] [DataPlane] enqueuing policy default/policy-with-cidr-except in netPolQueue
I0710 23:28:34.775273       1 dataplane.go:408] [DataPlane] [ADD-NETPOL] new pending netpol count: 1
I0710 23:28:34.775288       1 networkPolicyController.go:191] Successfully synced 'default/policy-with-cidr-except'
I0710 23:28:35.148630       1 dataplane.go:421] [DataPlane] adding policies [0xc000338d10]
I0710 23:28:35.148828       1 dataplane.go:330] [DataPlane] [ApplyDataPlane] [ADD-NETPOL] starting to apply ipsets
I0710 23:28:35.148870       1 ipsetmanager.go:455] [IPSetManager] dirty caches. toAddUpdateCache: to create: [], to update: [cidr-policy-with-cidr-except-in-ns-default-0-1IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-3IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-7OUT: &{membersToAdd:map[10.1.5.0/24 nomatch:{}] membersToDelete:map[10.1.4.0/24 nomatch:{}]},cidr-policy-with-cidr-except-in-ns-default-0-3OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-0IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-5IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-1OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-2OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-6IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-7IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-0OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-5OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-6OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-2IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-4IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-4OUT: &{membersToAdd:map[] membersToDelete:map[]}], toDeleteCache: map[]
I0710 23:28:35.148947       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 1, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
I0710 23:28:35.151875       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 2, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
I0710 23:28:35.154507       1 restore.go:188] running this restore command: [ipset restore]
I0710 23:28:35.157913       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 3, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 4, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
I0710 23:28:35.168315       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] error: failed to apply ipsets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
E0710 23:28:35.172634       1 dataplane.go:431] [DataPlane] [BACKGROUND] failed to add policies. will retry one policy at a time. err: [DataPlane] [ADD-NETPOL] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] [DataPlane] [BACKGROUND] failed to add policies. err: [DataPlane] [ADD-NETPOL] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
I0710 23:28:35.174607       1 dataplane.go:330] [DataPlane] [ApplyDataPlane] [ADD-NETPOL] starting to apply ipsets
I0710 23:28:35.174659       1 ipsetmanager.go:455] [IPSetManager] dirty caches. toAddUpdateCache: to create: [], to update: [cidr-policy-with-cidr-except-in-ns-default-0-1OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-3OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-0IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-5IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-0OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-2OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-6IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-7IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-4OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-5OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-6OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-2IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-4IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-7OUT: &{membersToAdd:map[10.1.5.0/24 nomatch:{}] membersToDelete:map[10.1.4.0/24 nomatch:{}]},cidr-policy-with-cidr-except-in-ns-default-0-1IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-3IN: &{membersToAdd:map[] membersToDelete:map[]}], toDeleteCache: map[]
I0710 23:28:35.174868       1 restore.go:188] running this restore command: [ipset restore]
I0710 23:28:35.177621       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 1, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
I0710 23:28:35.180657       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 2, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 3, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
I0710 23:28:35.185743       1 restore.go:188] running this restore command: [ipset restore]
I0710 23:28:35.187578       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 4, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]
2024/07/10 23:28:35 [1] error: failed to apply ipsets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] [DataPlane] [BACKGROUND] failed to add policy one at a time. default/policy-with-cidr-except. err: [DataPlane] [ADD-NETPOL] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
E0710 23:28:35.190302       1 dataplane.go:443] [DataPlane] [BACKGROUND] failed to add policy one at a time. policyKey: default/policy-with-cidr-except. err: [DataPlane] [ADD-NETPOL] error while applying IPSets: ipset restore failed when applying ipsets: Operation [RunCommandWithFile] failed with error code [999], full cmd [], full error after 5 tries, failed to run command [ipset restore] with error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
I0710 23:28:35.648957       1 dataplane.go:421] [DataPlane] adding policies [0xc000338d10]
I0710 23:28:35.649086       1 dataplane.go:330] [DataPlane] [ApplyDataPlane] [ADD-NETPOL] starting to apply ipsets
I0710 23:28:35.649173       1 ipsetmanager.go:455] [IPSetManager] dirty caches. toAddUpdateCache: to create: [], to update: [cidr-policy-with-cidr-except-in-ns-default-0-2IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-4IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-4OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-5OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-6OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-7OUT: &{membersToAdd:map[10.1.5.0/24 nomatch:{}] membersToDelete:map[10.1.4.0/24 nomatch:{}]},cidr-policy-with-cidr-except-in-ns-default-0-1IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-3IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-5IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-1OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-3OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-0IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-7IN: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-0OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-2OUT: &{membersToAdd:map[] membersToDelete:map[]},cidr-policy-with-cidr-except-in-ns-default-0-6IN: &{membersToAdd:map[] membersToDelete:map[]}], toDeleteCache: map[]
I0710 23:28:35.649334       1 restore.go:188] running this restore command: [ipset restore]
2024/07/10 23:28:35 [1] expected error with line number, but couldn't detect one with error regex pattern [Error in line (\d+):] for command [ipset restore] with stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]
2024/07/10 23:28:35 [1] error: on try number 1, failed to run command [ipset restore]. Rerunning with same file. err: [unknown error: error running command [ipset restore] with err [exit status 2] and stdErr [ipset v7.5: Unknown argument: `nomatch'
Try `ipset help' for more information.
]]

...
```

### CODE REVIEW

File: npm/pkg/dataplane/ipsets/ipsetmanager_linux.go [hunk 1]
```diff
@@ -774,6 +774,17 @@ func (iMgr *IPSetManager) deleteMemberForApply(creator *ioutil.FileCreator, set
 			},
 		},
 	}
+
+	splitMember := strings.Split(member, space)
```
Comment (timraymond) [inline npm/pkg/dataplane/ipsets/ipsetmanager_linux.go:778]: `[`strings.Fields`](https://pkg.go.dev/strings#Fields) is slightly better for this purpose since it considers all manner of what could constitute a "space". Granted, this is *probably* fine here given that `space` is likely the only one we'll encounter here. Just mentioning it for awareness more than anything.

**Review by timraymond — DISMISSED** [review]

File: npm/pkg/dataplane/ipsets/ipsetmanager_linux.go (hunk 1 above)
Comment (huntergregory) [reply npm/pkg/dataplane/ipsets/ipsetmanager_linux.go:778]: agh good call out, but ya for this use case there can only be a single space, added here:
https://github.com/Azure/azure-container-networking/blob/b29bdac938d49872cf19f383a65f325546612d12/npm/pkg/controlplane/translation/translatePolicy.go#L150

**Review by timraymond — APPROVED** [review]

**Review by matmerr — APPROVED** [review]
